export type REGIONS =
  | "westeurope"
  | "easteurope"
  | "southeurope"
  | "northeurope"
  | "centraleurope"
  | "middleeast"
  | "oceania"
  | "southamerica"
  | "northamerica"
  | "centralamerica"
  | "caribbean"
  | "southasia"
  | "eastasia"
  | "seasia"
  | "westasia"
  | "centralasia"
  | "northasia"
  | "pacific"
  | "northafrica"
  | "southafrica"
  | "easternafrica"
  | "westafrica"
  | "centralafrica"
  | "world";

export type LOCATIONS = "onsite" | "remote" | "hybrid";
